name: mapa_interactivo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: ^3.10.7

dependencies: 
  cupertino_icons: ^1.0.8
  get: 4.7.3
  flutter: 
    sdk: flutter
  flutter_staggered_animations: ^1.1.1

dev_dependencies: 
  flutter_lints: ^6.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - assets/
  uses-material-design: true

